//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Criteo.OpenApi.Comparator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Criteo.OpenApi.Comparator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity. Model definition &apos;{0}&apos; has extra properties [&apos;{1}&apos;]..
        /// </summary>
        internal static string AllowedTopLevelProperties {
            get {
                return ResourceManager.GetString("AllowedTopLevelProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline/anonymous models must not be used, instead define a schema with a model name in the &quot;definitions&quot; section and refer to it. This allows operations to share the models..
        /// </summary>
        internal static string AnonymousTypesDiscouraged {
            get {
                return ResourceManager.GetString("AnonymousTypesDiscouraged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Version must be in the format: yyyy-MM-dd, optionally followed by -preview, -alpha, -beta, -rc, -privatepreview..
        /// </summary>
        internal static string APIVersionFormatIsNotValid {
            get {
                return ResourceManager.GetString("APIVersionFormatIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top level property names should not be repeated inside the properties bag for ARM resource &apos;{0}&apos;. Properties [{1}] conflict with ARM top level properties. Please rename these..
        /// </summary>
        internal static string ArmPropertiesBagValidationMessage {
            get {
                return ResourceManager.GetString("ArmPropertiesBagValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoRest Core {0}.
        /// </summary>
        internal static string AutoRestCore {
            get {
                return ResourceManager.GetString("AutoRestCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property named: &apos;{0}&apos;, must follow camelCase style. Example: &apos;{1}&apos;..
        /// </summary>
        internal static string BodyPropertyNameCamelCase {
            get {
                return ResourceManager.GetString("BodyPropertyNameCamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booleans are not descriptive and make them hard to use. Instead use string enums with allowed set of values defined. Enum Property: {0}.
        /// </summary>
        internal static string BooleanPropertyNotRecommended {
            get {
                return ResourceManager.GetString("BooleanPropertyNotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection object &apos;{0}&apos; returned by list operation &apos;{1}&apos; with &apos;x-ms-pageable&apos; extension, has no property named &apos;value&apos;..
        /// </summary>
        internal static string CollectionObjectPropertiesNamingMessage {
            get {
                return ResourceManager.GetString("CollectionObjectPropertiesNamingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins:
        ///  CSharp:
        ///    TypeName: PluginCs, AutoRest.CSharp
        ///  JsonRpcClient:
        ///    TypeName: PluginCs, AutoRest.CSharp.JsonRpcClient
        ///  Azure.CSharp:
        ///    TypeName: PluginCsa, AutoRest.CSharp.Azure
        ///  Azure.CSharp.Fluent:
        ///    TypeName: PluginCsaf, AutoRest.CSharp.Azure.Fluent
        ///  Azure.JsonRpcClient:
        ///    TypeName: PluginCsa, AutoRest.CSharp.Azure.JsonRpcClient
        ///  Ruby:
        ///    TypeName: PluginRb, AutoRest.Ruby
        ///  Azure.Ruby:
        ///    TypeName: PluginRba, AutoRest.Ruby.Azure
        ///  NodeJS:
        ///    TypeName: PluginJs, Au [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigurationKnownPlugins {
            get {
                return ResourceManager.GetString("ConfigurationKnownPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property named: &apos;{0}&apos;, for definition: &apos;{1}&apos; must follow camelCase style. Example: &apos;{2}&apos;..
        /// </summary>
        internal static string DefinitionsPropertiesNameCamelCase {
            get {
                return ResourceManager.GetString("DefinitionsPropertiesNameCamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Delete&apos; operation &apos;{0}&apos; must not have a request body..
        /// </summary>
        internal static string DeleteMustNotHaveRequestBody {
            get {
                return ResourceManager.GetString("DeleteMustNotHaveRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;DELETE&apos; operation &apos;{0}&apos; must use method name &apos;Delete&apos;..
        /// </summary>
        internal static string DeleteOperationNameNotValid {
            get {
                return ResourceManager.GetString("DeleteOperationNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided for description is not descriptive enough. Accurate and descriptive description is essential for maintaining reference documentation..
        /// </summary>
        internal static string DescriptionNotDescriptive {
            get {
                return ResourceManager.GetString("DescriptionNotDescriptive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty x-ms-client-name property..
        /// </summary>
        internal static string EmptyClientName {
            get {
                return ResourceManager.GetString("EmptyClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating client model: {0}.
        /// </summary>
        internal static string ErrorGeneratingClientModel {
            get {
                return ResourceManager.GetString("ErrorGeneratingClientModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading {0} assembly: {1}.
        /// </summary>
        internal static string ErrorLoadingAssembly {
            get {
                return ResourceManager.GetString("ErrorLoadingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving generated code: {0}.
        /// </summary>
        internal static string ErrorSavingGeneratedCode {
            get {
                return ResourceManager.GetString("ErrorSavingGeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} not found.
        /// </summary>
        internal static string ExtensionNotFound {
            get {
                return ResourceManager.GetString("ExtensionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully initialized {0} Code Generator {1}.
        /// </summary>
        internal static string GeneratorInitialized {
            get {
                return ResourceManager.GetString("GeneratorInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;GET&apos; operation &apos;{0}&apos; must use method name &apos;Get&apos; or Method name start with &apos;List&apos;.
        /// </summary>
        internal static string GetOperationNameNotValid {
            get {
                return ResourceManager.GetString("GetOperationNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid used in model definition &apos;{1}&apos; for property &apos;{0}&apos;. Usage of Guid is not recommanded. If GUIDs are absolutely required in your service, please get sign off from the Azure API review board..
        /// </summary>
        internal static string GuidUsageNotRecommended {
            get {
                return ResourceManager.GetString("GuidUsageNotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissible values for HTTP Verb are delete,get,put,patch,head,options,post. .
        /// </summary>
        internal static string HttpVerbIsNotValid {
            get {
                return ResourceManager.GetString("HttpVerbIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing code generator..
        /// </summary>
        internal static string InitializingCodeGenerator {
            get {
                return ResourceManager.GetString("InitializingCodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing modeler..
        /// </summary>
        internal static string InitializingModeler {
            get {
                return ResourceManager.GetString("InitializingModeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter &apos;{0}&apos; must be a valid file path..
        /// </summary>
        internal static string InputMustBeAFile {
            get {
                return ResourceManager.GetString("InputMustBeAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value is not one of the values enumerated as valid for this element..
        /// </summary>
        internal static string InvalidDefault {
            get {
                return ResourceManager.GetString("InvalidDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name {0} cannot be used as an Identifier, as it contains only invalid characters..
        /// </summary>
        internal static string InvalidIdentifierName {
            get {
                return ResourceManager.GetString("InvalidIdentifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When property is modeled as &quot;readOnly&quot;: true then x-ms-mutability extension can only have &quot;read&quot; value. When property is modeled as &quot;readOnly&quot;: false then applying x-ms-mutability extension with only &quot;read&quot; value is not allowed. Extension contains invalid values: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidMutabilityValueForReadOnly {
            get {
                return ResourceManager.GetString("InvalidMutabilityValueForReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; code generator does not support code generation to a single file..
        /// </summary>
        internal static string LanguageDoesNotSupportSingleFileGeneration {
            get {
                return ResourceManager.GetString("LanguageDoesNotSupportSingleFileGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since operation &apos;{0}&apos; response has model definition &apos;{1}&apos;, it should be of the form &quot;*_list*&quot;.
        /// </summary>
        internal static string ListOperationsNamingWarningMessage {
            get {
                return ResourceManager.GetString("ListOperationsNamingWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;{0}&apos; operation &apos;{1}&apos; with x-ms-long-running-operation extension must have a valid terminal success status code {2}..
        /// </summary>
        internal static string LongRunningResponseNotValid {
            get {
                return ResourceManager.GetString("LongRunningResponseNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lacks &apos;description&apos; property. Consider adding a &apos;description&apos; element. Accurate description is essential for maintaining reference documentation..
        /// </summary>
        internal static string MissingDescription {
            get {
                return ResourceManager.GetString("MissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully initialized modeler {0} v {1}..
        /// </summary>
        internal static string ModelerInitialized {
            get {
                return ResourceManager.GetString("ModelerInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For better generated code quality, remove all references to &quot;msdn.microsoft.com&quot;..
        /// </summary>
        internal static string MsdnReferencesDiscouraged {
            get {
                return ResourceManager.GetString("MsdnReferencesDiscouraged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (already used in {1}).
        /// </summary>
        internal static string NamespaceConflictReasonMessage {
            get {
                return ResourceManager.GetString("NamespaceConflictReasonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that media types other than &apos;application/json&apos; are supported by your service..
        /// </summary>
        internal static string NonAppJsonTypeNotSupported {
            get {
                return ResourceManager.GetString("NonAppJsonTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 underscore is permitted in the operation id, following Noun_Verb conventions..
        /// </summary>
        internal static string OnlyOneUnderscoreAllowedInOperationId {
            get {
                return ResourceManager.GetString("OnlyOneUnderscoreAllowedInOperationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationId is required for all operations. Please add it for &apos;{0}&apos; operation of &apos;{1}&apos; path..
        /// </summary>
        internal static string OperationIdMissing {
            get {
                return ResourceManager.GetString("OperationIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationId has a noun that conflicts with one of the model names in definitions section. The model name will be disambiguated to &apos;{0}Model&apos;. Consider using the plural form of &apos;{1}&apos; to avoid this..
        /// </summary>
        internal static string OperationIdNounConflictingModelNamesMessage {
            get {
                return ResourceManager.GetString("OperationIdNounConflictingModelNamesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per the Noun_Verb convention for Operation Ids, the noun &apos;{0}&apos; should not appear after the underscore..
        /// </summary>
        internal static string OperationIdNounInVerb {
            get {
                return ResourceManager.GetString("OperationIdNounInVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;subscriptionId&quot; is not allowed in the operations section, define it in the global parameters section instead.
        /// </summary>
        internal static string OperationParametersNotAllowedMessage {
            get {
                return ResourceManager.GetString("OperationParametersNotAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations API must be implemented for &apos;{0}&apos;..
        /// </summary>
        internal static string OperationsAPINotImplemented {
            get {
                return ResourceManager.GetString("OperationsAPINotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Must have the &quot;name&quot; property defined with non-empty string as its value.
        /// </summary>
        internal static string ParametersPropertiesValidation {
            get {
                return ResourceManager.GetString("ParametersPropertiesValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is required..
        /// </summary>
        internal static string ParameterValueIsMissing {
            get {
                return ResourceManager.GetString("ParameterValueIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; value is not valid. Expect &apos;{1}&apos;.
        /// </summary>
        internal static string ParameterValueIsNotValid {
            get {
                return ResourceManager.GetString("ParameterValueIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PATCH&apos; operation &apos;{0}&apos; must use method name &apos;Update&apos;..
        /// </summary>
        internal static string PatchOperationNameNotValid {
            get {
                return ResourceManager.GetString("PatchOperationNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path cannot be null or an empty string or a string with white spaces while getting the parent directory.
        /// </summary>
        internal static string PathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("PathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has different responses for PUT/GET/PATCH operations. The PUT/GET/PATCH operations must have same schema response..
        /// </summary>
        internal static string PutGetPatchResponseInvalid {
            get {
                return ResourceManager.GetString("PutGetPatchResponseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;PUT&apos; operation &apos;{0}&apos; must use method name &apos;Create&apos;..
        /// </summary>
        internal static string PutOperationNameNotValid {
            get {
                return ResourceManager.GetString("PutOperationNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PUT operation request body schema should be the same as its 200 response schema, to allow reusing the same entity between GET and PUT. If the schema of the PUT request body is a superset of the GET response body, make sure you have a PATCH operation to make the resource updatable. Operation: &apos;{0}&apos; Request Model: &apos;{1}&apos; Response Model: &apos;{2}&apos;.
        /// </summary>
        internal static string PutOperationRequestResponseSchemaMessage {
            get {
                return ResourceManager.GetString("PutOperationRequestResponseSchemaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 200 response model for an ARM PUT operation must have x-ms-azure-resource extension set to true in its hierarchy. Operation: &apos;{0}&apos; Model: &apos;{1}&apos;..
        /// </summary>
        internal static string PutOperationResourceResponseValidationMessage {
            get {
                return ResourceManager.GetString("PutOperationResourceResponseValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is a required property. It should not be marked as &apos;readonly&apos;..
        /// </summary>
        internal static string RequiredReadOnlyPropertiesValidation {
            get {
                return ResourceManager.GetString("RequiredReadOnlyPropertiesValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;Resource&apos; definition must have x-ms-azure-resource extension enabled and set to true..
        /// </summary>
        internal static string ResourceIsMsResourceNotValid {
            get {
                return ResourceManager.GetString("ResourceIsMsResourceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model definition &apos;{0}&apos; must have the properties &apos;name&apos;, &apos;id&apos; and &apos;type&apos; in its hierarchy and these properties must be marked as readonly..
        /// </summary>
        internal static string ResourceModelIsNotValid {
            get {
                return ResourceManager.GetString("ResourceModelIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every swagger/configuration must have a security definitions section and it must adhere to the structure described in: https://github.com/Azure/autorest/tree/master/docs/developer/validation-rules/security-definitions-structure-validation.md.
        /// </summary>
        internal static string SecurityDefinitionsStructureValidation {
            get {
                return ResourceManager.GetString("SecurityDefinitionsStructureValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; is referenced but not defined in the global parameters section of Service Definition.
        /// </summary>
        internal static string ServiceDefinitionParametersMissingMessage {
            get {
                return ResourceManager.GetString("ServiceDefinitionParametersMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku Model definition &apos;{0}&apos; is not valid. A Sku model must have &apos;name&apos; property. It can also have &apos;tier&apos;, &apos;size&apos;, &apos;family&apos;, &apos;capacity&apos; as optional properties..
        /// </summary>
        internal static string SkuModelIsNotValid {
            get {
                return ResourceManager.GetString("SkuModelIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary and description values should not be same..
        /// </summary>
        internal static string SummaryDescriptionVaidationError {
            get {
                return ResourceManager.GetString("SummaryDescriptionVaidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Resource Management only supports HTTPS scheme..
        /// </summary>
        internal static string SupportedSchemesWarningMessage {
            get {
                return ResourceManager.GetString("SupportedSchemesWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked resource &apos;{0}&apos; must have a get operation..
        /// </summary>
        internal static string TrackedResourceGetOperationMissing {
            get {
                return ResourceManager.GetString("TrackedResourceGetOperationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The child tracked resource, &apos;{0}&apos; with immediate parent &apos;{1}&apos;, must have a list by immediate parent operation..
        /// </summary>
        internal static string TrackedResourceListByImmediateParentOperationMissing {
            get {
                return ResourceManager.GetString("TrackedResourceListByImmediateParentOperationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tracked resource, &apos;{0}&apos;, must have a list by resource group operation..
        /// </summary>
        internal static string TrackedResourceListByResourceGroupOperationMissing {
            get {
                return ResourceManager.GetString("TrackedResourceListByResourceGroupOperationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tracked resource, &apos;{0}&apos;, must have a list by subscriptions operation..
        /// </summary>
        internal static string TrackedResourceListBySubscriptionsOperationMissing {
            get {
                return ResourceManager.GetString("TrackedResourceListBySubscriptionsOperationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked resource &apos;{0}&apos; must have patch operation that at least supports the update of tags..
        /// </summary>
        internal static string TrackedResourcePatchOperationMissing {
            get {
                return ResourceManager.GetString("TrackedResourcePatchOperationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; name should be assembly qualified. For example &apos;ClassName, AssemblyName&apos;.
        /// </summary>
        internal static string TypeShouldBeAssemblyQualified {
            get {
                return ResourceManager.GetString("TypeShouldBeAssemblyQualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple resource providers are not allowed in a single spec. More than one the resource paths were found: &apos;{0}&apos;..
        /// </summary>
        internal static string UniqueResourcePaths {
            get {
                return ResourceManager.GetString("UniqueResourcePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a known format..
        /// </summary>
        internal static string UnknownFormat {
            get {
                return ResourceManager.GetString("UnknownFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;x-ms-client-name&apos; cannot be the same as &apos;{0}&apos; Property/Model..
        /// </summary>
        internal static string XmsClientNameInvalid {
            get {
                return ResourceManager.GetString("XmsClientNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the tracked resource &apos;{0}&apos;, the x-ms-pageable extension values must be same for list by resource group and subscriptions operations..
        /// </summary>
        internal static string XMSPagableListByRGAndSubscriptionsMismatch {
            get {
                return ResourceManager.GetString("XMSPagableListByRGAndSubscriptionsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths in x-ms-paths must overload a normal path in the paths section, i.e. a path in the x-ms-paths must either be same as a path in the paths section or a path in the paths sections followed by additional parameters..
        /// </summary>
        internal static string XMSPathBaseNotInPaths {
            get {
                return ResourceManager.GetString("XMSPathBaseNotInPaths", resourceCulture);
            }
        }
    }
}
