openapi: 3.1.0
info:
  version: 1.0.0
  title: Delta
webhooks:
  newPet:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        "200":
          description: ok
components:
  schemas:
    Pet:
      type: object
      properties:
        name:
          type: string
          maxLength: 20
        kind:
          type: string
          enum: [dog, cat, bird]
