openapi: 3.0.3
info:
  version: 1.0.0
  title: Delta
paths:
  /pets:
    get:
      operationId: listPets
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 0
            exclusiveMinimum: true
            maximum: 100
            exclusiveMaximum: true
      responses:
        "200":
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required: [name]
      properties:
        name:
          type: string
        tag:
          type: string
          nullable: true
        kind:
          type: string
          enum: [dog]
        count:
          type: integer
          enum: [1]
        status:
          type: string
          nullable: true
          enum: [a, b]
